config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise/registrations',
    passwords: 'devise/passwords'
  }
  resources :tops
  resources :homes
  resources :tops
  resources :homes
  resources :mypages
  resources :recodes
  resources :calendars
  resources :todopages
  resources :timetables
  resources :musics
  resource :profile,only: %i[show edit update]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root "tops#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
end

app/models/music.rb
class Music < ApplicationRecord
  mount_uploader :file, AudiofileUploader
end

app/models/recode.rb
class Recode < ApplicationRecord
  belongs_to :user
  validates :start_time, presence: true
  validates :finish_time, presence: true
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  belongs_to :user
  validates :start_time1, presence: true
  validates :finish_time1, presence: true
  validates :start_time2, presence: true
  validates :finish_time2, presence: true
  validates :start_time3, presence: true
  validates :finish_time3, presence: true
  validates :start_time4, presence: true
  validates :finish_time4, presence: true
  validates :start_time5, presence: true
  validates :finish_time5, presence: true
  validates :start_time6, presence: true
  validates :finish_time6, presence: true
end

app/models/todopage.rb
class Todopage < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recodes
  validates :name, presence: true, length: { minimum: 2 }

  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL ) do |user|
    user.password = SecureRandom.urlsafe_base64
    user.name = "guest"
    # user.confirmed_at = Time.now 
    # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  mount_uploader :avatar, AvatarUploader
  mount_uploader :backimage, BackimageUploader
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :authenticate_user!

  def index
      @musics = Music.all
      @music = Music.new
  end

  def new
      @music = Music.new
  end

  def create
      Music.create(music_params)
      redirect_to musics_path
  end

  def edit
      @music = Music.find(params[:id])
  end

  def update
      music = Music.find(params[:id])
      if music.update(music_params)
       redirect_to :action => "index"
      else
       render 'edit'
      end
  end

  def destroy
      @music = Music.find(params[:id])
      @music.destroy
      redirect_to musics_path
  end

  private

  def music_params
      params.require(:music).permit(:file)
  end

  
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/recodes_controller.rb
class RecodesController < ApplicationController
  before_action :authenticate_user!
  def index
      @recodes = Recode.all
  end

  def new
      @recode = Recode.new
  end

  def create
      recode = Recode.new(recode_params)
      recode.user_id = current_user.id
      if recode.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
  end

  def edit
      @recode = Recode.find(params[:id])
  end
  
  def update
     recode = Recode.find(params[:id])
     if recode.update(recode_params)
      redirect_to :action => "index", :id => recode.id
     else
      redirect_to :action => "new"
     end
  end

  def destroy
      recode = Recode.find(params[:id])
      recode.destroy
      redirect_to action: :index
  end

  private
  def recode_params
      params.require(:recode).permit(:title, :date, :content, :start_time, :finish_time)
  end
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
  before_action :authenticate_user!

  def index
      @timetables = Timetable.where(user_id: current_user.id).includes(:user).order("created_at DESC")
  end

  def new
      @timetable = Timetable.new
  end
  
  def create
      timetable = Timetable.create(timetable_params)
      timetable.user_id = current_user.id
      if timetable.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
  end

  def edit
      @timetable = Timetable.find(params[:id])
  end

  def update
      timetable = Timetable.find(params[:id])
      if timetable.update(timetable_params)
       redirect_to :action => "index"
      else
       render 'edit'
      end
  end

  def destroy
      @timetable = Timetable.find(params[:id])
      @timetable.destroy
      redirect_to timetables_path, notice:"削除しました"
  end

  private
  
  def timetable_params
    params.require(:timetable).permit( 
      :title11,
      :title12,
      :title13,
      :title14,
      :title15,
      :title16,
      :title21,
      :title22,
      :title23,
      :title24,
      :title25,
      :title26,
      :title31,
      :title32,
      :title33,
      :title34,
      :title35,
      :title36,
      :title41,
      :title42,
      :title43,
      :title44,
      :title45,
      :title46,
      :title51,
      :title52,
      :title53,
      :title54,
      :title55,
      :title56,
      :title61,
      :title62,
      :title63,
      :title64,
      :title65,
      :title66,
      :start_time1,
      :start_time2,
      :start_time3,
      :start_time4,
      :start_time5,
      :start_time6,
      :finish_time1,
      :finish_time2,
      :finish_time3,
      :finish_time4,
      :finish_time5,
      :finish_time6,
      :classroom11,
      :classroom12,
      :classroom13,
      :classroom14,
      :classroom15,
      :classroom16,
      :classroom21,
      :classroom22,
      :classroom23,
      :classroom24,
      :classroom25,
      :classroom26,
      :classroom31,
      :classroom32,
      :classroom33,
      :classroom34,
      :classroom35,
      :classroom36,
      :classroom41,
      :classroom42,
      :classroom43,
      :classroom44,
      :classroom45,
      :classroom46,
      :classroom51,
      :classroom52,
      :classroom53,
      :classroom54,
      :classroom55,
      :classroom56,
      :classroom61,
      :classroom62,
      :classroom63,
      :classroom64,
      :classroom65,
      :classroom66,
      :user_id,
  )
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/recodes_helper.rb
module RecodesHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/todopages_helper.rb
module TodopagesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/timetables/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>  

<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ホーム", homes_path, class: "sub_item" %></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
      <%= link_to homes_path, class: "items" do %>
        <i class="fas fa-home fa-lg fa-fw" ></i>ホーム
      <% end %>
      </li> 

      <li>
      <%= link_to mypages_path, class: "items" do %>
        <i class="fas fa-user fa-lg fa-fw"></i>マイページ
      <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
<div class="timetable_box">
  <h1 class="timetable_title">時間割編集</h1>
    <%= form_for @timetable do |f| %>
    <table border="1", class="timetable_table">
      <tr>
          <th>
          </th> 
          <th>月曜日</th> 
          <th>火曜日</th> 
          <th>水曜日</th> 
          <th>木曜日</th> 
          <th>金曜日</th> 
          <th>土曜日</th>
      </tr>

      <tr>
          <th>
          1<br>
          <%= f.time_field :start_time1 %> ～ <%= f.time_field :finish_time1, required:true %>
          </th> 
          <td>
          科目名：<%= f.text_field :title11 %><br>
          クラス：<%= f.text_field :classroom11 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title12 %><br>
          クラス：<%= f.text_field :classroom12 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title13 %><br>
          クラス：<%= f.text_field :classroom13 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title14 %><br>
          クラス：<%= f.text_field :classroom14 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title15 %><br>
          クラス：<%= f.text_field :classroom15 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title16 %><br>
          クラス：<%= f.text_field :classroom16 %><br>
          </td>
      </tr>

      <tr>
          <th>
          2<br>
          <%= f.time_field :start_time2 %> ～ <%= f.time_field :finish_time2, required:true %>
          </th> 
          <td>
          科目名：<%= f.text_field :title21 %><br>
          クラス：<%= f.text_field :classroom21 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title22 %><br>
          クラス：<%= f.text_field :classroom22 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title23 %><br>
          クラス：<%= f.text_field :classroom23 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title24 %><br>
          クラス：<%= f.text_field :classroom24 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title25 %><br>
          クラス：<%= f.text_field :classroom25 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title26 %><br>
          クラス：<%= f.text_field :classroom26 %><br>
          </td>
      </tr>

      <tr>
          <th>
          3<br>
          <%= f.time_field :start_time3 %> ～ <%= f.time_field :finish_time3, required:true %>
          </th> 
          <td>
          科目名：<%= f.text_field :title31 %><br>
          クラス：<%= f.text_field :classroom31 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title32 %><br>
          クラス：<%= f.text_field :classroom32 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title33 %><br>
          クラス：<%= f.text_field :classroom33 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title34 %><br>
          クラス：<%= f.text_field :classroom34 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title35 %><br>
          クラス：<%= f.text_field :classroom35 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title36 %><br>
          クラス：<%= f.text_field :classroom36 %><br>
          </td>
      </tr>

      <tr>
          <th>
          4<br>
          <%= f.time_field :start_time4 %> ～ <%= f.time_field :finish_time4, required:true  %>
          </th> 
          <td>
          科目名：<%= f.text_field :title41 %><br>
          クラス：<%= f.text_field :classroom41 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title42 %><br>
          クラス：<%= f.text_field :classroom42 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title43 %><br>
          クラス：<%= f.text_field :classroom43 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title44 %><br>
          クラス：<%= f.text_field :classroom44 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title45 %><br>
          クラス：<%= f.text_field :classroom45 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title46 %><br>
          クラス：<%= f.text_field :classroom46 %><br>
          </td>
      </tr>

      <tr>
          <th>
          5<br>
          <%= f.time_field :start_time5 %> ～ <%= f.time_field :finish_time5, required:true %>
          </th> 
          <td>
          科目名：<%= f.text_field :title51 %><br>
          クラス：<%= f.text_field :classroom51 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title52 %><br>
          クラス：<%= f.text_field :classroom52 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title53 %><br>
          クラス：<%= f.text_field :classroom53 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title54 %><br>
          クラス：<%= f.text_field :classroom54 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title55 %><br>
          クラス：<%= f.text_field :classroom55 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title56 %><br>
          クラス：<%= f.text_field :classroom56 %><br>
          </td>
      </tr>

      <tr>
          <th>
          6<br>
          <%= f.time_field :start_time6 %> ～ <%= f.time_field :finish_time6, required:true  %>
          </th> 
          <td>
          科目名：<%= f.text_field :title61 %><br>
          クラス：<%= f.text_field :classroom61 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title62 %><br>
          クラス：<%= f.text_field :classroom62 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title63 %><br>
          クラス：<%= f.text_field :classroom63 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title64 %><br>
          クラス：<%= f.text_field :classroom64 %><br>
          </td>
          <td>
          科目名：<%= f.text_field :title65 %><br>
          クラス：<%= f.text_field :classroom65 %><br>
          </td> 
          <td>
          科目名：<%= f.text_field :title66 %><br>
          クラス：<%= f.text_field :classroom66 %><br>
          </td>
      </tr>
    </table>
    <div class="timetable_submit_box">
      <%= f.submit "編集", class: "timetable_submit" %>
    </div>
  <% end %>
  <div class="timetable_back">
  <%= link_to "戻る", timetables_path %>
  </div>
</div>
</main>
</body>
</html>

app/views/timetables/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>timetable</title>
</head>

<body>

<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ホーム", homes_path, class: "sub_item" %></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
      <%= link_to homes_path, class: "items" do %>
        <i class="fas fa-home fa-lg fa-fw" ></i>ホーム
      <% end %>
      </li> 

      <li>
      <%= link_to mypages_path, class: "items" do %>
        <i class="fas fa-user fa-lg fa-fw"></i>マイページ
      <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
  <div class="timetable_box">
    <h1 class="timetable_title">時間割</h1>

    <div class="timetable_new_box">
    <%= link_to "時間割投稿", new_timetable_path, class:"timetable_new" %>
    </div>

    <% @timetables.each do |t| %>
        <table border="1", class="timetable_table">
            <tr>
                <th>
                </th> 
                <th>月曜日</th> 
                <th>火曜日</th> 
                <th>水曜日</th> 
                <th>木曜日</th> 
                <th>金曜日</th> 
                <th>土曜日</th>
            </tr>

            <tr>
                <th>
                1<br>
                <%= t.start_time1.strftime("%H:%M") %> ～ <%= t.finish_time1.strftime("%H:%M") %>
                </th> 
                <td>
                <%= t.title11 %><br>
                <%= t.classroom11 %><br>
                </td> 
                <td>
                <%= t.title12 %><br>
                <%= t.classroom12 %><br>
                </td> 
                <td>
                <%= t.title13 %><br>
                <%= t.classroom13 %><br>
                </td>
                <td>
                <%= t.title14 %><br>
                <%= t.classroom14 %><br>
                </td>
                <td>
                <%= t.title15 %><br>
                <%= t.classroom15 %><br>
                </td> 
                <td>
                <%= t.title16 %><br>
                <%= t.classroom16 %><br>
                </td>
            </tr>

            <tr>
                <th>
                2<br>
                <%= t.start_time2.strftime("%H:%M") %> ～ <%= t.finish_time2.strftime("%H:%M") %>
                </th> 
                <td>
                <%= t.title21 %><br>
                <%= t.classroom21 %><br>
                </td> 
                <td>
                <%= t.title22 %><br>
                <%= t.classroom22 %><br>
                </td> 
                <td>
                <%= t.title23 %><br>
                <%= t.classroom23 %><br>
                </td>
                <td>
                <%= t.title24 %><br>
                <%= t.classroom24 %><br>
                </td>
                <td>
                <%= t.title25 %><br>
                <%= t.classroom25 %><br>
                </td> 
                <td>
                <%= t.title26 %><br>
                <%= t.classroom26 %><br>
                </td>
            </tr>

            <tr>
                <th>
                3<br>
                <%= t.start_time3.strftime("%H:%M") %> ～ <%= t.finish_time3.strftime("%H:%M") %>
                </th> 
                <td>
                <%= t.title31 %><br>
                <%= t.classroom31 %><br>
                </td> 
                <td>
                <%= t.title33 %><br>
                <%= t.classroom33 %><br>
                </td> 
                <td>
                <%= t.title33 %><br>
                <%= t.classroom33 %><br>
                </td>
                <td>
                <%= t.title34 %><br>
                <%= t.classroom34 %><br>
                </td>
                <td>
                <%= t.title35 %><br>
                <%= t.classroom35 %><br>
                </td> 
                <td>
                <%= t.title36 %><br>
                <%= t.classroom36 %><br>
                </td>
            </tr>

            <tr>
                <th>
                4<br>
                <%= t.start_time4.strftime("%H:%M") %> ～ <%= t.finish_time4.strftime("%H:%M") %>
                </th> 
                <td>
                <%= t.title41 %><br>
                <%= t.classroom41 %><br>
                </td> 
                <td>
                <%= t.title42 %><br>
                <%= t.classroom42 %><br>
                </td> 
                <td>
                <%= t.title43 %><br>
                <%= t.classroom43 %><br>
                </td>
                <td>
                <%= t.title44 %><br>
                <%= t.classroom44 %><br>
                </td>
                <td>
                <%= t.title45 %><br>
                <%= t.classroom45 %><br>
                </td> 
                <td>
                <%= t.title46 %><br>
                <%= t.classroom46 %><br>
                </td>
            </tr>

            <tr>
                <th>
                5<br>
                <%= t.start_time5.strftime("%H:%M") %> ～ <%= t.finish_time5.strftime("%H:%M") %>
                </th> 
                <td>
                <%= t.title51 %><br>
                <%= t.classroom51 %><br>
                </td> 
                <td>
                <%= t.title52 %><br>
                <%= t.classroom52 %><br>
                </td> 
                <td>
                <%= t.title53 %><br>
                <%= t.classroom53 %><br>
                </td>
                <td>
                <%= t.title54 %><br>
                <%= t.classroom54 %><br>
                </td>
                <td>
                <%= t.title55 %><br>
                <%= t.classroom55 %><br>
                </td> 
                <td>
                <%= t.title56 %><br>
                <%= t.classroom56 %><br>
                </td>
            </tr>

            <tr>
                <th>
                6<br>
                <%= t.start_time6.strftime("%H:%M") %> ～ <%= t.finish_time6.strftime("%H:%M") %>
                </th> 
                <td>
                <%= t.title61 %><br>
                <%= t.classroom61 %><br>
                </td> 
                <td>
                <%= t.title62 %><br>
                <%= t.classroom62 %><br>
                </td> 
                <td>
                <%= t.title63 %><br>
                <%= t.classroom63 %><br>
                </td>
                <td>
                <%= t.title64 %><br>
                <%= t.classroom64 %><br>
                </td>
                <td>
                <%= t.title65 %><br>
                <%= t.classroom65 %><br>
                </td> 
                <td>
                <%= t.title66 %><br>
                <%= t.classroom66 %><br>
                </td>
            </tr>
        </table>

    <div class="timetable_option">
        <%= link_to edit_timetable_path(t.id), class: "timetable_edit" do %>
            <i class="fas fa-edit" ></i>編集
        <% end %>

        <%= link_to timetable_path(t.id), method: :delete, data: {confirm: "時間割の全ての項目が削除されます。本当に削除しますか？"}, class: "timetable_destroy" do %>
            <i class="fas fa-trash-alt"></i>消去
        <% end %>
    </div>
    <% end %>

    <div class="timetable_home">
    <%= link_to ">>Home", homes_path %>
    </div>
  </div>
</main>
</body>
</html>