config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise/registrations',
    passwords: 'devise/passwords'
  }
  resources :tops
  resources :homes
  resources :tops
  resources :homes
  resources :mypages
  resources :recodes
  resources :calendars
  resources :todopages
  resources :timetables
  resources :musics
  resource :profile,only: %i[show edit update]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root "tops#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
end

app/models/music.rb
class Music < ApplicationRecord
  mount_uploader :file, AudiofileUploader
end

app/models/recode.rb
class Recode < ApplicationRecord
  belongs_to :user
  validates :start_time, presence: true
  validates :finish_time, presence: true
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  belongs_to :user
  validates :start_time1, presence: true
  validates :finish_time1, presence: true
  validates :start_time2, presence: true
  validates :finish_time2, presence: true
  validates :start_time3, presence: true
  validates :finish_time3, presence: true
  validates :start_time4, presence: true
  validates :finish_time4, presence: true
  validates :start_time5, presence: true
  validates :finish_time5, presence: true
  validates :start_time6, presence: true
  validates :finish_time6, presence: true
end

app/models/todopage.rb
class Todopage < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recodes
  validates :name, presence: true, length: { minimum: 2 }

  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL ) do |user|
    user.password = SecureRandom.urlsafe_base64
    user.name = "guest"
    # user.confirmed_at = Time.now 
    # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  mount_uploader :avatar, AvatarUploader
  mount_uploader :backimage, BackimageUploader
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!
  def index
      @calendars = Calendar.where(user_id: current_user.id).includes(:user).order("created_at DESC")
      @calendar = Calendar.new
  end
      
  def new
      @calendar = Calendar.new
  end
    
  def show
      @calendar = Calendar.find(params[:id])
  end
    
  def create
      calendar = Calendar.create(calendar_parameter)
      calendar.user_id = current_user.id
        if calendar.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
  end
    
  def destroy
      @calendar = Calendar.find(params[:id])
      @calendar.destroy
      redirect_to calendars_path, notice:"削除しました"
  end
    
  def edit
      @calendar = Calendar.find(params[:id])
  end
    
  def update
      @calendar = Calendar.find(params[:id])
      if @calendar.update(calendar_parameter)
        redirect_to calendars_path, notice: "編集しました"
      else
        render 'edit'
      end
  end
    
  private
    
  def calendar_parameter
      params.require(:calendar).permit(:title, :content, :start_time)
  end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :authenticate_user!

  def index
      @musics = Music.all
      @music = Music.new
  end

  def new
      @music = Music.new
  end

  def create
      Music.create(music_params)
      redirect_to musics_path
  end

  def edit
      @music = Music.find(params[:id])
  end

  def update
      music = Music.find(params[:id])
      if music.update(music_params)
       redirect_to :action => "index"
      else
       render 'edit'
      end
  end

  def destroy
      @music = Music.find(params[:id])
      @music.destroy
      redirect_to musics_path
  end

  private

  def music_params
      params.require(:music).permit(:file)
  end

  
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/recodes_controller.rb
class RecodesController < ApplicationController
  before_action :authenticate_user!
  def index
      @recodes = Recode.all
  end

  def new
      @recode = Recode.new
  end

  def create
      recode = Recode.new(recode_params)
      recode.user_id = current_user.id
      if recode.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
  end

  def edit
      @recode = Recode.find(params[:id])
  end
  
  def update
     recode = Recode.find(params[:id])
     if recode.update(recode_params)
      redirect_to :action => "index", :id => recode.id
     else
      redirect_to :action => "new"
     end
  end

  def destroy
      recode = Recode.find(params[:id])
      recode.destroy
      redirect_to action: :index
  end

  private
  def recode_params
      params.require(:recode).permit(:title, :date, :content, :start_time, :finish_time)
  end
end

app/controllers/todopages_controller.rb
class TodopagesController < ApplicationController
  before_action :authenticate_user!

  def index
      @todopages = Todopage.where(user_id: current_user.id).includes(:user).order("created_at DESC")
      @todopage = Todopage.new 
  end

  def new
      @todopage = Todopage.new
  end
  
  def create
      todopage = Todopage.create(todopage_params)
      todopage.user_id = current_user.id
      if todopage.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
  end

  def edit
      @todopage = Todopage.find(params[:id])
  end

  def update
      todopage = Todopage.find(params[:id])
      if todopage.update(todopage_params)
       redirect_to :action => "index"
      else
       render 'edit'
      end
  end

  def destroy
      @todopage = Todopage.find(params[:id])
      @todopage.destroy
      redirect_to todopages_path, notice:"削除しました"
  end

  private
  
  def todopage_params
    params.require(:todopage).permit(:text)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/recodes_helper.rb
module RecodesHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/todopages_helper.rb
module TodopagesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/calendars/edit.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ホーム", homes_path, class: "sub_item" %></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
      <%= link_to homes_path, class: "items" do %>
        <i class="fas fa-home fa-lg fa-fw" ></i>ホーム
      <% end %>
      </li> 

      <li>
      <%= link_to mypages_path, class: "items" do %>
        <i class="fas fa-user fa-lg fa-fw"></i>マイページ
      <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
  <div class="calendar_edit_box">
    <h1 class="calendar_edit_title">スケジュール編集</h1>
    <%= form_with(model: @calendar, local: true) do |form| %>

      <div class="title">
        <div class="form-tag">タイトル</div>
        <%= form.text_field :title %>
      </div>


      <div class="content">
        <div class="form-tag">内容</div>
        <%= form.text_field :content %>
      </div>

      <div class="time">
        <div class="form-tag">時間</div>
        <%= form.datetime_select :start_time %>
      </div>

      <div class="calendar_edit_submit">
        <%= form.submit "変更する", class: "calendar_submit"  %>
      </div>
    <% end %>
  </div>
</main>

</body>
</html>

app/views/calendars/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>calendar</title>
</head>

<body>
<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ホーム", homes_path, class: "sub_item" %></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
      <%= link_to homes_path, class: "items" do %>
        <i class="fas fa-home fa-lg fa-fw" ></i>ホーム
      <% end %>
      </li> 

      <li>
      <%= link_to mypages_path, class: "items" do %>
        <i class="fas fa-user fa-lg fa-fw"></i>マイページ
      <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
  <h1 class="top">Calendar</h1>

  <div class="col-md-8">
    <%= month_calendar events: @calendars do |date, calendars| %>
    <%= date.day %>
      <% calendars.each do |calendar| %>
        <div class="txt-limit">
          <%= link_to calendar.title.truncate(5), calendar %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-4">
    <div class="schedule-title">カレンダー予定</div>
      <%= form_with(model: @calendar, local: true) do |form| %>

        <div class="title">
          <div class="form-tag">タイトル</div>
          <%= form.text_field :title, required: true, style: "width:80%" %>
        </div>


        <div class="content">
          <div class="form-tag">内容</div>
          <%= form.text_field :content, required: true, style: "width:80%" %>
        </div>

        <div class="time">
          <div class="form-tag">時間</div>
          <%= form.datetime_select :start_time %>
        </div>

        <div class="calendar_submit_box">
          <%= form.submit "予定を登録", class: "calendar_submit" %>
        </div>
      <% end %>

    <div class="calendar_home">
      <%= link_to ">> Home", homes_path %>
    </div>
  </div>

</main>
</body>
</html>

app/views/calendars/show.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>calendar</title>
</head>

<body>
<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ホーム", homes_path, class: "sub_item" %></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
      <%= link_to homes_path, class: "items" do %>
        <i class="fas fa-home fa-lg fa-fw" ></i>ホーム
      <% end %>
      </li> 

      <li>
      <%= link_to mypages_path, class: "items" do %>
        <i class="fas fa-user fa-lg fa-fw"></i>マイページ
      <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
  <h1 class="top">Calendar</h1>

  <div class="col-md-8">
    <%= month_calendar events: @calendars do |date, calendars| %>
    <%= date.day %>
      <% calendars.each do |calendar| %>
        <div class="txt-limit">
          <%= link_to calendar.title.truncate(5), calendar %>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-4">
    <div class="schedule-title">カレンダー予定</div>
      <%= form_with(model: @calendar, local: true) do |form| %>

        <div class="title">
          <div class="form-tag">タイトル</div>
          <%= form.text_field :title, required: true, style: "width:80%" %>
        </div>


        <div class="content">
          <div class="form-tag">内容</div>
          <%= form.text_field :content, required: true, style: "width:80%" %>
        </div>

        <div class="time">
          <div class="form-tag">時間</div>
          <%= form.datetime_select :start_time %>
        </div>

        <div class="calendar_submit_box">
          <%= form.submit "予定を登録", class: "calendar_submit" %>
        </div>
      <% end %>

    <div class="calendar_home">
      <%= link_to ">> Home", homes_path %>
    </div>
  </div>

</main>
</body>
</html>

app/views/musics/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>music</title>
</head>
<body>

<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ホーム", homes_path, class: "sub_item" %></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
      <%= link_to homes_path, class: "items" do %>
        <i class="fas fa-home fa-lg fa-fw" ></i>ホーム
      <% end %>
      </li> 

      <li>
      <%= link_to mypages_path, class: "items" do %>
        <i class="fas fa-user fa-lg fa-fw"></i>マイページ
      <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
    <h1 class="music_title" >Music</h1>
      <p class="music_sample" >&lt; サンプル音源 &gt;</p>

    <div class="flex-container">
      <div class="sample_music">
        <p>BGM </p>
        <!-- audio_tag 音楽再生-->
        <%= audio_tag "10℃.mp3", :controls => true %>
      </div>

      <div class="sample_music">
        <p>BGM2 </p>
        <!-- audio_tag 音楽再生-->
        <%= audio_tag "BGM2.mp3", :controls => true %>
      </div>

      <div class="sample_music">
        <p>環境音</p>
        <!-- audio_tag 音楽再生-->
        <%= audio_tag "nature.mp3", :controls => true %>
      </div>

      <div class="sample_music">
        <p>クラシック 「月の光」</p>
        <!-- audio_tag 音楽再生-->
        <%= audio_tag "classic.mp3", :controls => true %>
      </div>

      <div class="sample_music">
        <p>jazz 「Tea for Two」</p>
        <!-- audio_tag 音楽再生-->
        <%= audio_tag "Tea For Two.mp3", :controls => true %>
      </div>

      <div class="sample_music">
        <p>jazz 「Someday my prince will come」</p>
        <!-- audio_tag 音楽再生-->
        <%= audio_tag "Someday my prince will come.mp3", :controls => true %>
      </div>
    </div>

<!--音楽投稿-->
        <p class="form-title" >&lt; 音源ファイル投稿 &gt;</p>
        <div class="audio-form">
          <%= form_with(model: @music, local: true) do |f| %>
                <%= f.file_field :file %>
                <%= button_tag f.submit %>
          <% end %>
        </div>

    <!--投稿された音楽再生-->
    <div class="music_upload">
      <% @musics.each do |t| %>
          <audio src= "<%= "#{t.file}" %>" controls >
          <a src="<%= "#{t.file}" %>">ダウンロード</a>
          </audio>
      <p style><%= link_to "削除", music_path(t.id), method: :delete %></p>
      <% end %>
    </div>

</main>
</body>
</html>

app/views/recodes/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>学習記録Tweets</title>
</head>
<body>

<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ホーム", homes_path, class: "sub_item" %></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
      <%= link_to homes_path, class: "items" do %>
        <i class="fas fa-home fa-lg fa-fw" ></i>ホーム
      <% end %>
      </li> 

      <li>
      <%= link_to mypages_path, class: "items" do %>
        <i class="fas fa-user fa-lg fa-fw"></i>マイページ
      <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
  <div class="recodes_box">
    <h1 class="recodes_title">学習記録Tweets</h1>

    <!--新規投稿ボタン-->
    <%= link_to new_recode_path, class: "recodes_new" do%>
      <i class="fa-solid fa-circle-plus"></i>
    <% end %>

    <!--投稿表示-->
    <div class="recodes_container_box">
      <% @recodes.each do |t| %>
        <div class="recode_box">
            <% if t.user.guest_user? %>
              <%= image_tag "sample.jpg", class: 'icon_cycle_image', size: '50x50' %>
            <% else %>
              <%= image_tag t.user.avatar.url, class: 'icon_cycle_image', size: '50x50' %>
            <% end %>

            <div class="recode_name" >
              <%= t.user.name %>
            </div>

            <div class="recode_date">
              <%= t.date %>
            </div>

            <div class="recode_time" >
              学習時間 :<%= t.start_time.strftime("%H:%M") %> ～ <%= t.finish_time.strftime("%H:%M") %><br>
            </div>

            <div class="recode_content">
              学習内容 :<%= t.content %><br>
            </div>

            <div class="recode_option">
              <%= link_to recode_path(t.id), method: :delete, class: "recode_destroy" do %>
                <i class="fas fa-trash-alt"></i>
              <% end %>
              <%= link_to edit_recode_path(t.id), class: "recode_edit" do %>
                <i class="fas fa-edit" ></i>
              <% end %>
            </div>       
        </div>
      <% end %>
    </div>
    <div class="home_back">
      <%= link_to ">> Home", homes_path %>
    </div>
  </div>

</main>
</body>
</html>

app/views/todopages/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todoリスト</title>
</head>

<body>
<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ホーム", homes_path, class: "sub_item" %></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
      <%= link_to homes_path, class: "items" do %>
        <i class="fas fa-home fa-lg fa-fw" ></i>ホーム
      <% end %>
      </li> 

      <li>
      <%= link_to mypages_path, class: "items" do %>
        <i class="fas fa-user fa-lg fa-fw"></i>マイページ
      <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
  <div class="boxes">
    <h1 class="todo-title">Todo リスト</h1>
    <%= form_with(model: @todopage, local: true) do |f| %>
      <div class="field-container">
        <%= f.text_field :text, required: true, maxlength: 60 %>
        <%= button_tag type: "submit", class: "send-icon" do %>
          <i class="fa fa-send"></i>
        <% end %>
      </div>
    <% end %>

    <div class="boxes-inner"></div>
    <div class="text-container">
      <% @todopages.each do |t| %>
        <div class="text-field">
          <%= t.text %>
          <div class="todo_option" >
            <%= link_to todopage_path(t.id), method: :delete, class: "todo_destroy" do %>
              <i class="fas fa-trash-alt"></i>
            <% end %>
            <%= link_to edit_todopage_path(t.id), class: "todo_edit" do %>
              <i class="fas fa-edit" ></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <p class="home-box"><%= link_to "<< Home", homes_path, class: "home-box" %></p>
  </div>
</main>
</body>
</html>