config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'devise/registrations',
    passwords: 'devise/passwords'
  }
  resources :tops
  resources :homes
  resources :tops
  resources :homes
  resources :mypages
  resources :recodes
  resources :calendars
  resources :todopages
  resources :timetables
  resources :musics
  resource :profile,only: %i[show edit update]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root "tops#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
end

app/models/music.rb
class Music < ApplicationRecord
  mount_uploader :file, AudiofileUploader
end

app/models/recode.rb
class Recode < ApplicationRecord
  belongs_to :user
  validates :start_time, presence: true
  validates :finish_time, presence: true
end

app/models/timetable.rb
class Timetable < ApplicationRecord
  belongs_to :user
  validates :start_time1, presence: true
  validates :finish_time1, presence: true
  validates :start_time2, presence: true
  validates :finish_time2, presence: true
  validates :start_time3, presence: true
  validates :finish_time3, presence: true
  validates :start_time4, presence: true
  validates :finish_time4, presence: true
  validates :start_time5, presence: true
  validates :finish_time5, presence: true
  validates :start_time6, presence: true
  validates :finish_time6, presence: true
end

app/models/todopage.rb
class Todopage < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recodes
  validates :name, presence: true, length: { minimum: 2 }

  GUEST_USER_EMAIL = "guest@example.com"
  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL ) do |user|
    user.password = SecureRandom.urlsafe_base64
    user.name = "guest"
    # user.confirmed_at = Time.now 
    # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  mount_uploader :avatar, AvatarUploader
  mount_uploader :backimage, BackimageUploader
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!
  def index
      @calendars = Calendar.where(user_id: current_user.id).includes(:user).order("created_at DESC")
      @calendar = Calendar.new
  end
      
  def new
      @calendar = Calendar.new
  end
    
  def show
      @calendar = Calendar.find(params[:id])
  end
    
  def create
      calendar = Calendar.create(calendar_parameter)
      calendar.user_id = current_user.id
        if calendar.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
  end
    
  def destroy
      @calendar = Calendar.find(params[:id])
      @calendar.destroy
      redirect_to calendars_path, notice:"削除しました"
  end
    
  def edit
      @calendar = Calendar.find(params[:id])
  end
    
  def update
      @calendar = Calendar.find(params[:id])
      if @calendar.update(calendar_parameter)
        redirect_to calendars_path, notice: "編集しました"
      else
        render 'edit'
      end
  end
    
  private
    
  def calendar_parameter
      params.require(:calendar).permit(:title, :content, :start_time)
  end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :authenticate_user!

  def index
      @musics = Music.all
      @music = Music.new
  end

  def new
      @music = Music.new
  end

  def create
      Music.create(music_params)
      redirect_to musics_path
  end

  def edit
      @music = Music.find(params[:id])
  end

  def update
      music = Music.find(params[:id])
      if music.update(music_params)
       redirect_to :action => "index"
      else
       render 'edit'
      end
  end

  def destroy
      @music = Music.find(params[:id])
      @music.destroy
      redirect_to musics_path
  end

  private

  def music_params
      params.require(:music).permit(:file)
  end

  
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/recodes_controller.rb
class RecodesController < ApplicationController
  before_action :authenticate_user!
  def index
      @recodes = Recode.all
  end

  def new
      @recode = Recode.new
  end

  def create
      recode = Recode.new(recode_params)
      recode.user_id = current_user.id
      if recode.save
        redirect_to :action => "index"
      else
        redirect_to :action => "new"
      end
  end

  def edit
      @recode = Recode.find(params[:id])
  end
  
  def update
     recode = Recode.find(params[:id])
     if recode.update(recode_params)
      redirect_to :action => "index", :id => recode.id
     else
      redirect_to :action => "new"
     end
  end

  def destroy
      recode = Recode.find(params[:id])
      recode.destroy
      redirect_to action: :index
  end

  private
  def recode_params
      params.require(:recode).permit(:title, :date, :content, :start_time, :finish_time)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/recodes_helper.rb
module RecodesHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/todopages_helper.rb
module TodopagesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/homes/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Top page</title>
</head>

<body>

<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
        <%= link_to destroy_user_session_path, method: :delete, class: "items" do %>
          <i class="fas fa-sign-out fa-lg fa-fw" ></i>ログアウト
        <% end %>
      </li> 

      <li>
        <%= link_to mypages_path, class: "items" do %>
          <i class="fas fa-user fa-lg fa-fw"></i>マイページ
        <% end %>
      </li>

      <li>
        <% if current_user.guest_user? %>
        <p class=items>ゲスト閲覧中</p>
        <% else %>
        <%= link_to edit_profile_path, class: "items" do %>
          <i class="fas fa-user-edit fa-lg fa-fw"></i>ユーザー
        <% end %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
<!--slick -->
  <div class="previews">
    <ul class="slider">
      <li>
        <%= image_tag 'desk.jpg' %>
        <span class="inner_title">
          <p>学習サポートサイト</p>
          <%= link_to " Study Link",tops_path, class: "link-text" %>
        </span>
      </li>
      <li>
        <%= image_tag 'Todo.jpg'%>
        <span class="inner_title">
          <p>タスクを一括管理</p>
          <%= link_to " Todo List ",todopages_path, class: "link-text"  %>
        </span>
      </li>
      <li>
        <%= image_tag 'post.jpg'%>
        <span class="inner_title" >
          <p>学習記録を共有</p>
          <%= link_to " Recodes ", recodes_path, class: "link-text"  %>
        </span></li>
      <li>
        <%= image_tag 'calendar.jpg'%>
          <span class="inner_title">
            <p>スケジュール管理</p>
            <%= link_to " calendar ", calendars_path, class: "link-text"  %>
          </span></li>
    </ul>
  </div>
<!--slick 閉じ-->

<!--画像より下のテキスト-->
  <div class="top-box">
    <p class="notice-text" ><%= current_user.name%>さんがログインしています</p>
    <h1 class="title-box">Study Link</h1>
  </div>

  <div class="about-box fadeLeftTrigger"> <!--JS スクロール左から出現 -->
    <h2 class="about-title">About</h2>
    <p>
      <span>学習サポートサイトStudy Linkへようこそ!</span> <br>
      <span>Study Linkは、</span>
      <span><strong>大学生向けのタスク、学習管理アプリ</strong>です。</span> <br>
      <span>当サイトは、学習と知識の共有を推奨し、</span>
      <span>人々がスキルを向上させることで,</span> <br>
      <span>新しい知識を獲得できる場を提供しています!</span> <br>
    <p>
    <p> &gt; &gt;まずは<%= link_to " ログイン", new_user_session_path %></p>
  </div>

  <div class="cando-box fadeRightTrigger"> <!--JS スクロール左から出現 -->
    <h2 class="cando-title">Can do</h2>
    <p>
      <span>当サイトの魅力は以下の点にあります！</span> <br>
      <span>・面倒なスケジュール管理をサイトで<strong>一括化！</strong></span> <br>
      <span>・スマホでも使える<strong>レスポンシブ対応！</strong> </span> <br>
      <span>・使いやすい<strong>シンプルなデザイン！</strong></span> <br>
      <span>・<strong>学習記録を共有</strong>してモチベーションアップ！</span> <br>
      <span>・<strong>音楽</strong>を流して気分アップ♪</span> <br>
      <span>以上をもとに、あなたのなりの学習サイトを</span>
      <span>カスタマイズできます。</span> <br>
    </p>
    <p> &gt; &gt;<%= link_to " マイページ", mypages_path %></p>
  </div>

  <div class="Music-box fadeLeftTrigger"> <!--JS スクロール左から出現 -->
    <h2 class="Music-title">Music</h2>
    <p>
      <span>集中力アップのため、環境音やジャズなどの</span>
      <span>音源を用意しています。</span> <br>
      <span>まるでカフェにいるかのような環境で</span>
      <span>勉強しましょう！</span> <br>
      <span>好きな音楽をアップロードして</span>
      <span>聴くことも可能です!</span> <br>
    </p>
      <p class="sample">サンプル音源</p>
    <!-- audio_tag 音楽再生-->
    <%= audio_tag "sample.mp3", :controls => true %> <!--動作不安定 :autoplay => trueで自動再生可 -->
    <p> &gt; &gt;<%= link_to " 音楽ページ", musics_path %></p>
  </div>

  <!--Contents-->
  <div class="top-box">
    <h1 class="title-box">Contents</h1>
  </div>

  <div class="contents-box">
    <h2 class="Todo-title">Todoリスト</h2>
      <p>大学での課題やレポートの出し忘れを防ぎます。</p>
      <p> &gt;&gt;ページは<%= link_to "こちら", todopages_path %></p>

    <h2 class="Calendar-title">Calendar</h2>
      <p>スケジュール管理もこれひとつ！</p>
      <p> &gt;&gt;ページは<%= link_to "こちら", calendars_path %></p>

    <h2 class="Timetables-title">時間割</h2>
      <p>大学の時間割を管理しよう!</p>
      <p> &gt;&gt;ページは<%= link_to "こちら", timetables_path %></p>

    <h2 class="Tweets-title">学習Tweet</h2>
      <p>学習した記録を友達と共有しよう！</p>
      <p> &gt;&gt;ページは<%= link_to "こちら", recodes_path %></p>
  </div>
</main>
</body>
</html>

app/views/mypages/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mypage</title>
</head>

<body>

<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", homes_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ホーム", homes_path, class: "sub_item" %></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "sub_item"  %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
      <%= link_to homes_path, class: "items" do %>
        <i class="fas fa-home fa-lg fa-fw" ></i>ホーム
      <% end %>
      </li> 

      <li>
      <%= link_to mypages_path, class: "items" do %>
        <i class="fas fa-user fa-lg fa-fw"></i>マイページ
      <% end %>
      </li>

      <li>
        <% if current_user.guest_user? %>
        <p class=items>ゲスト閲覧中</p>
        <% else %>
        <%= link_to edit_profile_path, class: "items" do %>
          <i class="fas fa-user-edit fa-lg fa-fw"></i>ユーザー
        <% end %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
  <div class="container_box">
    <!--背景画像 -->
    <p class="back_color">
      <%= image_tag current_user.backimage.url, class: "backimage" %>
    </p>
    <!--js 時刻表示 -->
    <div class="time_box">
      <p id="days", class="days"></p>
      <p id="realtime", class="realtime"></p>
    </div>
    
    <!--プロフィール-->
    <div class="profile_mainbox">
      <div>
        <% if current_user.guest_user? %>  
          <p><%= image_tag "sample.jpg", class: "icon_image" %></p>  <!--ゲストならサンプルアイコン-->
        <% else %>
          <p><%= image_tag current_user.avatar.url, class: "icon_image" %></p>  <!--ゲスト以外のユーザーは登録or初期アイコン -->
        <% end %>
      </div>

      <div class="profile_box">
        <h1 class="profile_text">プロフィール</h1>
        <ul>
          <% if current_user.guest_user? %>
            <li>※ゲストユーザーは編集できません</li>
            <li>メールアドレス : <%= current_user.email %></li>
            <li>ユーザ : <%= current_user.name %></li>
          <% else %>
            <li>メールアドレス : <%= current_user.email %></li>
            <li>ユーザ : <%= current_user.name %></li>
            <li>性別 : <%= current_user.gender %></li>
            <li>年齢 : <%= current_user.age %></li>
            <li>出身地 : <%= current_user.address %></li>
            <%= link_to '編集', edit_profile_path %>
            <%= link_to 'パスワード変更', edit_user_registration_path %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</body>
</html>




app/views/tops/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Top page</title>
</head>

<body>
<!--ヘッダー-->
<header>  
<!--ヘッダーロゴ-->
  <div class="main_logo">
    <%= link_to "StudyLink", tops_path, class: "logo" %>
  </div>

<!--ハンバーガーメニュー-->
  <div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
  </div>

<!--スマホ用ハンバーガーメニューのリスト-->
  <nav class="sm">
    <ul class="list">  <%# このサイト参照 https://zenn.dev/ganmo3/articles/8ae23a01dd1206 %>
      <li><%= link_to "ログイン", new_user_session_path, class: "sub_item" %></li>
      <li><%= link_to "新規登録", new_user_registration_path, class: "sub_item" %></li>
      <li><%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "sub_item"%></li>
      <li><%= link_to "マイページ", mypages_path, class: "sub_item"%></li>
      <li><%= link_to "TODOリスト", todopages_path, class: "sub_item" %></li>
      <li><%= link_to "カレンダー", calendars_path, class: "sub_item" %></li>
      <li><%= link_to "時間割", timetables_path, class: "sub_item" %></li>
      <li><%= link_to "学習記録投稿", recodes_path, class: "sub_item" %></li>
      <li><%= link_to "音楽ページ", musics_path, class: "sub_item" %></li>
    </ul>
  </nav>

<!--pc用ヘッダーリスト-->
  <nav class="pc">  <!--pcクラスを追記-->
    <ul class="pc_list">
    <!-- Fontawesome + 文字でリンク -->
      <li>
        <%= link_to new_user_session_path, class: "items" do %>
          <i class="fas fa-sign-in fa-lg fa-fw" ></i>ログイン
        <% end %>
      </li> 

      <li>
        <%= link_to new_user_registration_path, class: "items" do %>
          <i class="fas fa-user-plus fa-lg fa-fw"></i> 新規登録
        <% end %>
      </li>
      <li>
        <%= link_to users_guest_sign_in_path, method: :post, class: "items" do%>
          <i class="fas fa-user-circle fa-lg fa-fw"></i> ゲスト
        <% end %>
      </li>
    </ul>
  </nav>
</header>
<!-- ヘッダー閉じ -->

<main>
<!--slick -->
  <div class="previews">
    <ul class="slider">
      <li>
        <%= image_tag 'desk.jpg' %>
        <span class="inner_title">
          <p>学習サポートサイト</p>
          <%= link_to " Study Link",tops_path, class: "link-text" %>
        </span>
      </li>
      <li>
        <%= image_tag 'Todo.jpg'%>
        <span class="inner_title">
          <p>タスクを一括管理</p>
          <%= link_to " Todo List ",todopages_path, class: "link-text"  %>
        </span>
      </li>
      <li>
        <%= image_tag 'post.jpg'%>
        <span class="inner_title" >
          <p>学習記録を共有</p>
          <%= link_to " Recodes ", recodes_path, class: "link-text"  %>
        </span></li>
      <li>
        <%= image_tag 'calendar.jpg'%>
          <span class="inner_title">
            <p>スケジュール管理</p>
            <%= link_to " calendar ", calendars_path, class: "link-text"  %>
          </span></li>
    </ul>
  </div>
<!--slick 閉じ-->

<!--画像より下のテキスト-->
  <div class="top-box">
    <h1 class="title-box">Study Link</h1>
  </div>

  <div class="about-box fadeLeftTrigger"> <!--JS スクロール左から出現 -->
    <h2 class="about-title">About</h2>
    <p>
      <span>学習サポートサイトStudy Linkへようこそ!</span> <br>
      <span>Study Linkは、</span>
      <span><strong>大学生向けのタスク、学習管理アプリ</strong>です。</span> <br>
      <span>当サイトは、学習と知識の共有を推奨し、</span>
      <span>人々がスキルを向上させることで,</span> <br>
      <span>新しい知識を獲得できる場を提供しています!</span> <br>
    <p>
    <p> &gt; &gt;まずは<%= link_to " ログイン", new_user_session_path %></p>
  </div>

  <div class="cando-box fadeRightTrigger"> <!--JS スクロール左から出現 -->
    <h2 class="cando-title">Can do</h2>
    <p>
      <span>当サイトの魅力は以下の点にあります！</span> <br>
      <span>・面倒なスケジュール管理をサイトで<strong>一括化！</strong></span> <br>
      <span>・スマホでも使える<strong>レスポンシブ対応！</strong> </span> <br>
      <span>・使いやすい<strong>シンプルなデザイン！</strong></span> <br>
      <span>・<strong>学習記録を共有</strong>してモチベーションアップ！</span> <br>
      <span>・<strong>音楽</strong>を流して気分アップ♪</span> <br>
      <span>以上をもとに、あなたのなりの学習サイトを</span>
      <span>カスタマイズできます。</span> <br>
    </p>
    <p> &gt; &gt;<%= link_to " マイページ", mypages_path %></p>
  </div>

  <div class="Music-box fadeLeftTrigger"> <!--JS スクロール左から出現 -->
    <h2 class="Music-title">Music</h2>
    <p>
      <span>集中力アップのため、環境音やジャズなどの</span>
      <span>音源を用意しています。</span> <br>
      <span>まるでカフェにいるかのような環境で</span>
      <span>勉強しましょう！</span> <br>
      <span>好きな音楽をアップロードして</span>
      <span>聴くことも可能です!</span> <br>
    </p>
    <p class="sample">サンプル音源</p>
    <!-- audio_tag 音楽再生-->
    <%= audio_tag "sample.mp3", :controls => true %> <!--動作不安定 :autoplay => trueで自動再生可 -->
    <p> &gt; &gt;<%= link_to " 音楽ページ", musics_path %></p>
  </div>

  <!--Contents-->
  <div class="top-box">
    <h1 class="title-box">Contents</h1>
  </div>

  <div class="contents-box">
    <h2 class="Todo-title">Todoリスト</h2>
      <p>大学での課題やレポートの出し忘れを防ぎます!</p>
      <p> &gt;&gt;ページは<%= link_to "こちら", todopages_path %></p>

    <h2 class="Calendar-title">Calendar</h2>
      <p>スケジュール管理もこれひとつ！</p>
      <p> &gt;&gt;ページは<%= link_to "こちら", calendars_path %></p>

    <h2 class="Timetables-title">時間割</h2>
      <p>大学の時間割を管理しよう!</p>
      <p> &gt;&gt;ページは<%= link_to "こちら", timetables_path %></p>

    <h2 class="Tweets-title">学習Tweet</h2>
      <p>学習した記録を友達と共有しよう！</p>
      <p> &gt;&gt;ページは<%= link_to "こちら", recodes_path %></p>
  </div>

</main>
  <!--JS ローディングアニメーション-->
  <div class="start">
    <p class="start_logo">
      <%= image_tag '2.jpg', class: "start_image" %>
    </p>
  </div>
</body>
</html>